
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Footer, SideNav } from '@/components'
import '@radix-ui/themes/styles.css';
import { Theme } from '@radix-ui/themes';
import '@radix-ui/themes/styles.css';


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Stephen Leachman',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Theme>
        <div className="fixed">
          <SideNav />
        </div>
          <div className="ml-[90px]">
           
            {children}
            <Footer />
          </div>
        </Theme>
      </body>
    </html>
  )
}
